Repository UMC-UNIVEUS/UNIVEUS-backend, pull requests merged in 2023-08, with the labels that each got.

#25 Add : /user/start/univeus 유니버스 시작하기 구현
  config/jwtMiddleWare.js
  config/response.js
  src/app/user/userController.js
  src/app/user/userDao.js
  src/app/user/userRoute.js
  src/app/user/userService.js
Labels: enhancement

#29 Fix : 로그인 ec2 테스트
  src/app/user/userController.js
Labels: enhancement

#33 게시글 스크랩, 좋아요 API
  config/response.js
  package-lock.json
  package.json
  src/app/comment/commController.js
  src/app/comment/commProvider.js
  src/app/comment/commService.js
  src/app/post/postController.js
  src/app/post/postDao.js
  src/app/post/postProvider.js
  src/app/post/postRoute.js
  src/app/post/postService.js
  src/app/user/userController.js
  src/app/user/userDao.js
  src/app/user/userProvider.js
Labels: enhancement

#44 Add : 게시글 신고 API
  src/app/report/reportController.js
  src/app/report/reportDao.js
  src/app/report/reportRoute.js
  src/app/report/reportService.js
Labels: enhancement

#46 유니버스 참여 API + 알림 API
  config/response.js
  src/app/comment/commController.js
  src/app/comment/commDao.js
  src/app/comment/commService.js
  src/app/post/postController.js
  src/app/post/postDao.js
  src/app/post/postProvider.js
  src/app/post/postRoute.js
  src/app/post/postService.js
  src/app/user/userController.js
  src/app/user/userDao.js
  src/app/user/userProvider.js
  src/app/user/userRoute.js
  src/app/user/userService.js
Labels: enhancement

#48 Add : /?category=1&sorted=1&page=1 메인페이지 페이징처리 및 카테고리 & 인기순 & 최신순 정렬
  config/express.js
  src/app/main/mainController.js
  src/app/main/mainDao.js
  src/app/main/mainProvider.js
  src/app/main/mainRoute.js
  src/app/main/mainService.js
Labels: enhancement

#51 Update: 게시글, 댓글에 JWT 미들웨어 추가
  src/app/comment/commController.js
  src/app/comment/commDao.js
  src/app/comment/commRoute.js
  src/app/comment/commService.js
  src/app/post/postController.js
  src/app/post/postDao.js
  src/app/post/postRoute.js
  src/app/post/postService.js
Labels: enhancement

#52 Fix: 쿼리문 수정
  src/app/post/postController.js
  src/app/post/postDao.js
  src/app/post/postRoute.js
Labels: enhancement

#55 Update: 게시글, 댓글 예외처리
  config/response.js
  src/app/comment/commController.js
  src/app/comment/commDao.js
  src/app/comment/commService.js
  src/app/post/postController.js
  src/app/post/postDao.js
  src/app/post/postService.js
Labels: update

#56 Add : 메인페이지 구현
  package-lock.json
  package.json
  src/app/main/mainController.js
  src/app/main/mainDao.js
  src/app/main/mainProvider.js
  src/app/main/mainRoute.js
  src/app/main/mainService.js
Labels: enhancement

#58 Add : main 페이지 작성자 정보 추가
  src/app/main/mainDao.js
  src/app/main/mainService.js
Labels: enhancement

#60 Add: 유니버스 참여 (축제용)
  src/app/post/postController.js
  src/app/post/postDao.js
  src/app/post/postRoute.js
  src/app/post/postService.js
Labels: enhancement

#62 Add: 유니버스 참여자 초대
  config/database.js
  config/response.js
  src/app/post/postController.js
  src/app/post/postDao.js
  src/app/post/postRoute.js
  src/app/post/postService.js
  src/app/user/userDao.js
  src/app/user/userProvider.js
Labels: enhancement

#63 Add: 게시글 참여 자동 마감
  config/response.js
  src/app/post/postController.js
  src/app/post/postDao.js
  src/app/post/postProvider.js
  src/app/post/postService.js
Labels: enhancement

#64 Update: 유니버스 참여 시 인원 +1
  src/app/post/postDao.js
  src/app/post/postService.js
Labels: update

#65 Feat : 내가 만든 유니버스, 참여한 유니버스 조회 API
  config/express.js
  config/response.js
  package-lock.json
  package.json
  src/app/profile/profileController.js
  src/app/profile/profileDao.js
  src/app/profile/profileProvider.js
  src/app/profile/profileRoute.js
Labels: enhancement

#67 유니버스 모집 마감 수정
  config/response.js
  package-lock.json
  src/app/post/postController.js
  src/app/post/postDao.js
  src/app/post/postRoute.js
Labels: update

#69 Add: 유니버스 참여 취소 (축제용)
  src/app/post/postController.js
  src/app/post/postDao.js
  src/app/post/postProvider.js
  src/app/post/postRoute.js
  src/app/post/postService.js
Labels: enhancement

#72 Update: 유니버스 참여
  config/response.js
  src/app/post/postController.js
Labels: update

#74 Add : 이미지 업로드 구현
  config/imageUploader.js
  src/app/post/postController.js
  src/app/post/postRoute.js
Labels: enhancement

#77 Update: 유니버스 참여자 초대
  src/app/post/postController.js
  src/app/user/userController.js
  src/app/user/userDao.js
  src/app/user/userProvider.js
Labels: update

#78 Update: 유니버스 참여, Add: 신고하기 문자 알림 (to 관리자)
  config/response.js
  src/app/post/postController.js
  src/app/post/postService.js
  src/app/report/reportController.js
  src/app/user/userController.js
Labels: enhancement, update

#80 Fix : 로그인 회원가입 기능 병합, cors 해결
  config/response.js
  src/app/main/mainDao.js
  src/app/user/userController.js
  src/app/user/userDao.js
  src/app/user/userRoute.js
  src/app/user/userService.js
Labels: enhancement

#82 Add : Access-Control-Allow-Origin 추가
  config/express.js
Labels: bug fix

#86 Update : cors 해결 + 코드 리팩토링
  src/app/user/userController.js
  src/app/user/userProvider.js
  src/app/user/userService.js
Labels: enhancement
