Repository UMC-UNIVEUS/UNIVEUS-backend, pull requests merged in 2023-09, with the labels that each got.

#88 Update: 축제용 코드
  src/app/post/postController.js
  src/app/post/postDao.js
  src/app/post/postRoute.js
  src/app/post/postService.js
  src/app/user/userController.js
Labels: update

#90 Update : 검색 예외처리
  config/response.js
  src/app/main/mainController.js
  src/app/main/mainDao.js
Labels: update

#92 Add: 모집 마감(수동), Update: 게시글, 유저 정보 조회 함수
  config/response.js
  src/app/post/postController.js
  src/app/post/postDao.js
  src/app/post/postProvider.js
  src/app/post/postRoute.js
  src/app/post/postService.js
  src/app/report/reportController.js
  src/app/user/userController.js
  src/app/user/userDao.js
  src/app/user/userProvider.js
  src/app/user/userService.js
Labels: enhancement, update

#94 본인인증 기능분리
  config/jwtMiddleWare.js
  config/response.js
  src/app/user/userController.js
  src/app/user/userDao.js
  src/app/user/userProvider.js
  src/app/user/userRoute.js
  src/app/user/userService.js
Labels: update

#98 Update: 게시글 작성과 동시에 참여자 초대
  config/response.js
  src/app/post/postController.js
  src/app/post/postDao.js
  src/app/post/postService.js
Labels: update

#99 Update: 게시글 작성 예외 처리
  src/app/post/postController.js
  src/app/post/postRoute.js
Labels: update

#100 Add: 관리자 페이지 : 유저 정보확인
  config/express.js
  config/response.js
  package.json
  src/app/admin/adminController.js
  src/app/admin/adminDao.js
  src/app/admin/adminProvider.js
  src/app/admin/adminRoute.js
  src/app/admin/adminService.js
  src/app/user/userProvider.js
Labels: enhancement

#102 Add: 관리자 페이지 : 유저 정보확인
  src/app/admin/adminDao.js
  src/app/admin/adminProvider.js
  src/app/admin/adminRoute.js
  src/app/admin/adminService.js
Labels: enhancement

#103 Fix : 병합 오류(누락코드) 추가
  config/express.js
  src/app/admin/adminController.js
Labels: bug fix

#104 Add: 관리자 게시물 관리
  config/response.js
  src/app/admin/adminController.js
  src/app/admin/adminDao.js
  src/app/admin/adminRoute.js
  src/app/admin/adminService.js
  src/app/post/postController.js
  src/app/post/postService.js
Labels: enhancement

#105 Add: 게시글 작성 (관리자)
  src/app/admin/adminController.js
  src/app/admin/adminRoute.js
Labels: enhancement

#107 Update : 메인 페이지 조회 시 Response 수정
  src/app/main/mainDao.js
  src/app/main/mainProvider.js
Labels: enhancement

#108 번호인증 동시성문제 해결
  config/response.js
  src/app/admin/adminController.js
  src/app/admin/adminRoute.js
  src/app/admin/adminService.js
  src/app/user/userController.js
  src/app/user/userDao.js
  src/app/user/userService.js
Labels: enhancement, bug fix

#110 Add: 게시글 작성 문자 알림
  config/NaverCloudClient.js
  src/app/post/postController.js
  src/app/user/userController.js
Labels: enhancement

#111 Update: 게시글 작성 시 알림
  config/response.js
  src/app/post/postController.js
  src/app/post/postService.js
  src/app/user/userController.js
Labels: enhancement

#114 Update: 게시글 참여 시 문자 알림
  src/app/post/postController.js
  src/app/post/postDao.js
  src/app/post/postService.js
  src/app/user/userController.js
Labels: update

#115 Add : 관리자 확인 미들웨어 추가
  config/adminMiddleware.js
  config/authUserMiddleware.js
  src/app/admin/adminController.js
  src/app/admin/adminDao.js
  src/app/admin/adminRoute.js
Labels: enhancement

#120 Update: 게시글 참여
  src/app/post/postController.js
  src/app/user/userController.js
Labels: update

#123 Update : 유저 신고 및 신고 사유 DB 테이블 병합에 따른 API 수정
  src/app/report/reportController.js
  src/app/report/reportDao.js
  src/app/report/reportService.js
  src/app/user/userController.js
Labels: update

#125 Update : 게시글 신고 및 신고 사유 DB 테이블 병합에 따른 API 수정
  src/app/report/reportController.js
  src/app/report/reportDao.js
  src/app/report/reportService.js
Labels: update

#126 Updete: 이미지 관련 API
  config/response.js
  src/app/post/postController.js
  src/app/post/postDao.js
  src/app/post/postProvider.js
  src/app/post/postService.js
Labels: enhancement, update

#128 Add : 신고 유저 확인
  config/express.js
  src/app/admin/adminController.js
  src/app/admin/adminDao.js
  src/app/admin/adminProvider.js
  src/app/admin/adminRoute.js
  src/app/views/index.ejs
  src/app/views/nav.html
  src/app/views/signup.ejs
  src/app/views/user.ejs
  src/app/views/userInfo.ejs
  src/app/views/userReports.ejs
Labels: enhancement

#129 Update: 참여하기 알림
  src/app/post/postController.js
  src/app/user/userController.js
Labels: update

#130 Fix: git 충돌
  src/app/post/postRoute.js
Labels: bug fix

#132 Update : 알림 Response 수정(유니버스 작성, 참여)
  src/app/user/userController.js
Labels: enhancement

#133 Add : [관리자] 유저관리 - 유저 제제
  src/app/admin/adminController.js
  src/app/admin/adminDao.js
  src/app/admin/adminProvider.js
  src/app/admin/adminRoute.js
  src/app/report/reportDao.js
  src/app/report/reportService.js
  src/app/user/userDao.js
  src/app/user/userService.js
  src/app/views/nav.html
  src/app/views/userBlock.ejs
  src/app/views/userReports.ejs
Labels: enhancement

#135 Add : 유저 제재 해제 구현
  src/app/admin/adminController.js
  src/app/admin/adminRoute.js
  src/app/report/reportDao.js
  src/app/report/reportService.js
  src/app/views/userReports.ejs
Labels: enhancement

#138 Issue/97
  config/response.js
  src/app/post/postController.js
  src/app/post/postRoute.js
  src/app/user/userController.js
Labels: update

#140 Update : 신고 당한 유저 reported_num 증가, 3번 이상 신고 당한 유저 탈퇴 진행
  src/app/admin/adminController.js
  src/app/admin/adminProvider.js
  src/app/user/userDao.js
  src/app/user/userProvider.js
  src/app/user/userService.js
Labels: update

#142 Add : 로그인 기본 유저 정보 조회 시 성별 관련 필드 추가
  src/app/profile/profileDao.js
Labels: enhancement

#143 Update : 미들웨어로 유저의 계정 상태 확인
  config/accountStatusMiddleware.js
  config/response.js
  src/app/admin/adminController.js
  src/app/main/mainRoute.js
  src/app/report/reportRoute.js
  src/app/user/userDao.js
  src/app/user/userProvider.js
  src/app/user/userRoute.js
Labels: update

#145 Update : 미들웨어로 유저의 계정 상태 확인
  config/accountStatusMiddleware.js
  config/response.js
  src/app/admin/adminController.js
  src/app/main/mainRoute.js
  src/app/report/reportRoute.js
  src/app/user/userDao.js
  src/app/user/userProvider.js
  src/app/user/userRoute.js
Labels: update

#148 Add : 본인인증 후 가입 메세지 보내기
  src/app/user/userController.js
  src/app/user/userDao.js
  src/app/user/userProvider.js
Labels: update

#150 Update: 응답 처리
  config/response.js
  src/app/post/postController.js
  src/app/post/postDao.js
Labels: update

#151 Update: 상세 조회 API
  src/app/post/postController.js
Labels: update

#155 Update: 게시글 작성, 참여하기 예외 처리
  config/response.js
  src/app/post/postController.js
Labels: update

#156 Update : 게시글 상세 조회 시 날짜 response 변경
  src/app/post/postController.js
Labels: update

#157 Update : 게시물 상세 조회 API Response 수정
  src/app/post/postController.js
Labels: update

#158 Update: 게시글 조회
  src/app/post/postController.js
Labels: update

#160 Update : 검색 isMyPost 추가, main 및 검색 페이지 날짜 포맷팅
  src/app/main/mainController.js
  src/app/main/mainProvider.js
  src/app/main/mainRoute.js
  src/app/post/postController.js
  src/app/post/postProvider.js
  src/app/user/userController.js
Labels: update

#162 Add : 에러 핸들러 추가
  config/errorhandler.js
  config/naverCloudClient.js
  src/app/admin/adminRoute.js
  src/app/comment/commRoute.js
  src/app/main/mainRoute.js
  src/app/post/postRoute.js
  src/app/profile/profileRoute.js
  src/app/report/reportRoute.js
  src/app/user/userRoute.js
Labels: enhancement

#165 Update : 배포용 서버 주석 해제
  config/jwtMiddleWare.js
  src/app/user/userController.js
Labels: update

#167 Update: 게시글 조회 시 다른 게시글 참여 확인
  src/app/post/postController.js
  src/app/post/postDao.js
  src/app/post/postService.js
  src/app/user/userDao.js
  src/app/user/userProvider.js
Labels: update

#169 Update: 게시글 조회
  src/app/post/postController.js
Labels: update

#170 Fix : 인증번호 문제 해결
  config/response.js
  src/app/user/userController.js
Labels: bug fix

#171 Fix: git 충돌
  src/app/post/postRoute.js
Labels: bug fix

#174 Fix : 인증번호 if 조건문 문 추가
  src/app/user/userController.js
Labels: bug fix

#175 Fix : 인증번호 bug fix
  src/app/user/userController.js
Labels: bug fix

#177 Fix : 닉네임 이모지 공백 삭제 처리
  src/app/user/userController.js
  src/app/user/userProvider.js
Labels: bug fix

#179 Fix : 유니버스 시작하기 버그 수정
  src/app/user/userController.js
Labels: bug fix

#182 Update : 내가 참여한 유니버스, 내가 작성한 유니버스 날짜 포맷팅
  src/app/post/postProvider.js
  src/app/profile/profileProvider.js
Labels: update

#186 Update : 유니버스 created_at 포맷팅
  src/app/post/postController.js
  src/app/post/postProvider.js
  src/app/profile/profileProvider.js
  src/app/user/userProvider.js
Labels: update

#187 Fix : 유니버스 참여하기 예외처리
  src/app/post/postController.js
Labels: bug fix

#188 Update : 유니버스 참여하기 예외처리, 코드 리팩토링
  config/response.js
  src/app/post/postController.js
  src/app/post/postDao.js
  src/app/post/postService.js
Labels: update, bug fix

#189 Fix : 유니버스 시작하기 예외처리
  src/app/post/postController.js
Labels: bug fix

#193 Update : 게시글 early return 패턴 적용하여 리팩토링 + 참여하기 예외처리
  config/response.js
  src/app/post/postController.js
Labels: enhancement, update

#194 Update : 예외처리
  src/app/post/postController.js
Labels: update, bug fix

#195 Update : 예외처리 테스트
  src/app/post/postController.js
Labels: update, bug fix

#196 Update : console.log 삭제
  src/app/post/postController.js
  src/app/user/userController.js
Labels: update

#198 Update : 게시글 작성하기 코드리팩토링 + 예외처리
  src/app/post/postController.js
  src/app/user/userController.js
Labels: update, bug fix

#201 Add : 카카오톡 오픈채팅 유효성 검사 추가
  config/response.js
  src/app/post/postController.js
  src/app/post/postProvider.js
  src/app/post/postRoute.js
Labels: enhancement

#203 Update : isParticipateOtherPost main페이지 추가
  src/app/main/mainController.js
  src/app/main/mainRoute.js
  src/app/main/mainService.js
  src/app/user/userProvider.js
Labels: update

#205 Update : 삭제를 요청하는 사람과 글 작성자가 일치하는 지 확인하는 로직 변경
  src/app/post/postController.js
Labels: enhancement

#206 Update : isParticipateOtherPost 형식 수정
  src/app/main/mainController.js
  src/app/main/mainService.js
  src/app/user/userProvider.js
Labels: update

#208 Fix : 유니버스 시작하기 버그 수정
  src/app/user/userController.js
  src/app/user/userDao.js
  src/app/user/userService.js
Labels: bug fix

#209 Update : 이미 참여한 게시글이 있다면 다른 게시글 참여 불가하게 participate_available 추가
  config/response.js
  src/app/main/mainController.js
  src/app/post/postController.js
  src/app/post/postRoute.js
  src/app/user/userDao.js
  src/app/user/userProvider.js
  src/app/user/userService.js
Labels: update

#211 Upate: 조건문
  src/app/post/postController.js
Labels: update

#212 Update: 알림 문자 주석 해체
  src/app/post/postController.js
Labels: update

#217 Update : 이미지 업로드 관련 문제 해결
  config/imageUploader.js
  config/response.js
  package-lock.json
  package.json
  src/app/post/postRoute.js
Labels: enhancement

#218 develop 수정 사항을 main에 merge
  config/imageUploader.js
  config/response.js
  package-lock.json
  package.json
  src/app/post/postRoute.js
Labels: update

#219 Update: 문자 알림 형식
  src/app/user/userController.js
Labels: update

#220 Update: 문자 알림 형식 (to main)
  src/app/user/userController.js
Labels: update

#221 삭제되면 다시 참여권 주기, 매칭 되었을 때 삭제 안 되게
  config/response.js
  src/app/post/postController.js
  src/app/post/postRoute.js
  src/app/user/userDao.js
  src/app/user/userService.js
Labels: update

#222 삭제할 때 참여권 반환 추가
  config/response.js
  src/app/post/postController.js
  src/app/post/postRoute.js
  src/app/user/userDao.js
  src/app/user/userService.js
Labels: update

#225 Update: 주석 처리 해제
  src/app/user/userController.js
Labels: update

#227 Add : 애널리틱스 추가
  src/app/user/userController.js
  src/app/user/userDao.js
  src/app/user/userProvider.js
  src/app/user/userRoute.js
Labels: update

#228 Update: 게시글 참여 신청 (실서비스용)
  config/response.js
  src/app/post/postController.js
  src/app/post/postDao.js
  src/app/post/postRoute.js
  src/app/post/postService.js
Labels: update

#230 Issue/700 merge to develop
  config/response.js
  src/app/post/postController.js
  src/app/post/postDao.js
  src/app/post/postProvider.js
  src/app/post/postRoute.js
  src/app/post/postService.js
  src/app/user/userController.js
  src/app/user/userDao.js
  src/app/user/userProvider.js
  src/app/user/userRoute.js
Labels: update

#231 Update: 게시글 참여자 승인
  src/app/post/postController.js
Labels: update

#232 Update: 코드 리펙토링
  config/response.js
  src/app/post/postController.js
Labels: update

#233 Update: JWT 유효시간
  src/app/post/postController.js
  src/app/user/userController.js
Labels: update

#234 Update: 문자 알림 주석 처리
  src/app/post/postController.js
Labels: update

#235 Add: 찜한 게시글 조회
  src/app/profile/profileController.js
  src/app/profile/profileDao.js
  src/app/profile/profileProvider.js
  src/app/profile/profileRoute.js
Labels: enhancement

#236 Update: 게시글 조회 시 댓글까지 조회 + 찜한 게시글 예외처리
  config/response.js
  src/app/comment/commDao.js
  src/app/post/postController.js
  src/app/post/postRoute.js
  src/app/profile/profileProvider.js
  src/app/profile/profileRoute.js
Labels: update

#237 Add: 게시글 좋아요 취소
  src/app/post/postController.js
  src/app/post/postDao.js
  src/app/post/postRoute.js
  src/app/post/postService.js
Labels: enhancement

#240 Add: 게시글 스크랩 취소
  src/app/post/postController.js
  src/app/post/postDao.js
  src/app/post/postRoute.js
  src/app/post/postService.js
Labels: enhancement
