Repository UMC-UNIVEUS/UNIVEUS-backend, pull requests merged in 2024-01, with the labels that each got.

#21 [Bug Fix]: 로그인 에러
  config/response.js
  src/app/user/userController.js
  src/app/user/userDao.js
  src/app/user/userProvider.js
  src/app/user/userService.js
Labels: 🚑 Bug Fix

#23 🔨 Refactor : 유저 번호인증 코드 리펙토링
  src/app/user/userController.js
  src/app/user/userDao.js
  src/app/user/userProvider.js
Labels: 🔨 Refactoring

#27 Refactor : 유저 소속등록 코드 리펙토링
  config/response.js
  src/app/user/userController.js
  src/app/user/userDao.js
  src/app/user/userRoute.js
  src/app/user/userService.js
Labels: 🔨 Refactoring

#29 Refactor : 유저 reponse 코드 리펙토링
  config/response.js
  src/app/user/userController.js
Labels: 🔨 Refactoring

#31 Feat : 유저 profile 등록
  config/response.js
  src/app/user/userController.js
  src/app/user/userDao.js
  src/app/user/userRoute.js
  src/app/user/userService.js
Labels: 🔨 Refactoring

#33 Refactor : 로그인 리다이렉트 response 테스트
  config/response.js
  src/app/user/userController.js
  src/app/user/userDao.js
  src/app/user/userProvider.js
Labels: 🔨 Refactoring

#36 🔨 [Refectoring]: develop 코드 게시글 코드에 pull 받기
  config/express.js
  config/response.js
  src/app/post/postController.js
  src/app/post/postDao.js
  src/app/post/postDto.js
  src/app/post/postProvider.js
  src/app/post/postRoute.js
  src/app/post/postService.js
  src/app/user/userController.js
  src/app/user/userDao.js
  src/app/user/userProvider.js
  src/app/user/userService.js
Labels: 🔨 Refactoring

#38 Add : 프로필 mbti 조회 API 테스트
  src/app/profile/profileController.js
  src/app/profile/profileDao.js
  src/app/profile/profileProvider.js
  src/app/profile/profileRequestDTO.js
  src/app/profile/profileResponseDTO.js
  src/app/profile/profileRoute.js
  src/app/profile/profileService.js
Labels: ✨ Feat

#39 Fix : profileDao 쪽 오타 수정
  src/app/profile/profileDao.js
Labels: 🚑 Bug Fix

#42 Refactoring : 유저 신고 기능 코드 리팩토링
  config/response.js
  src/app/report/reportController.js
  src/app/report/reportDao.js
  src/app/report/reportRoute.js
  src/app/report/reportService.js
  src/app/user/userController.js
Labels: 🔨 Refactoring

#44 [Bug Fix]: 게시글 조회 API
  src/app/post/postController.js
  src/app/user/userProvider.js
Labels: 🚑 Bug Fix

#47 Fix : 이미지 업로드 문제 해결
  config/imageUploader.js
  src/app/profile/profileController.js
  src/app/profile/profileDao.js
  src/app/profile/profileProvider.js
  src/app/profile/profileResponseDTO.js
Labels: 🚑 Bug Fix

#48 Fix : 이미지 업로드 시 생기는 확장자 문제 해결
  config/imageUploader.js
  config/response.js
  src/app/profile/profileDao.js
  src/app/profile/profileResponseDTO.js
Labels: 🚑 Bug Fix

#49 Issue/46
  src/app/post/postController.js
  src/app/post/postDao.js
Labels: 🔨 Refactoring

#52 Feat : N문 N답(=남이 보는 프로필) 조회 API 완성
  config/response.js
  src/app/profile/profileController.js
  src/app/profile/profileDao.js
  src/app/profile/profileProvider.js
  src/app/profile/profileRequestDTO.js
  src/app/profile/profileResponseDTO.js
  src/app/profile/profileRoute.js
Labels: ✨ Feat

#54 Refactor : N문 N답 관련 api 코드 구조 개선 & 예외 처리
  config/response.js
  src/app/profile/profileController.js
  src/app/profile/profileDao.js
  src/app/profile/profileProvider.js
  src/app/profile/profileRequestDTO.js
  src/app/profile/profileResponseDTO.js
  src/app/profile/profileService.js
Labels: 🚑 Bug Fix, 🔨 Refactoring

#55 Feat : 유저 프로필 조회 API 완성(유저 정보, 생성 정보, 참여 정보)
  config/response.js
  src/app/post/postProvider.js
  src/app/profile/profileController.js
  src/app/profile/profileDao.js
  src/app/profile/profileProvider.js
  src/app/profile/profileResponseDTO.js
  src/app/profile/profileRoute.js
Labels: ✨ Feat

#56 Feat : 유저 프로필 정보 수정 API 완성
  config/response.js
  src/app/profile/profileController.js
  src/app/profile/profileDao.js
  src/app/profile/profileRequestDTO.js
  src/app/profile/profileResponseDTO.js
  src/app/profile/profileRoute.js
  src/app/profile/profileService.js
Labels: ✨ Feat

#57 Fix : N문 N답 조회 API 코드 오류 수정
  src/app/profile/profileProvider.js
  src/app/profile/profileRoute.js
Labels: 🚑 Bug Fix
