Repository UMC-UNIVEUS/UNIVEUS-backend, pull requests merged in 2024-02, with the labels that each got.

#65 Fix : 내 프로필 조회(참여 정보) 시 중복 조회되는 문제 제거
  src/app/profile/profileDao.js
Labels: 🚑 Bug Fix

#66 Refactoring : 로그인 로직 변경 프론트에서 인가토큰 받는 방식으로 변경
  src/app/user/userController.js
  src/app/user/userRoute.js
Labels: 🚑 Bug Fix, 🔨 Refactoring

#67 Feat : 메인 페이지 게시글 조회 API, 검색 API 구현
  config/response.js
  src/app/main/mainController.js
  src/app/main/mainDao.js
  src/app/main/mainProvider.js
  src/app/main/mainRequestDTO.js
  src/app/main/mainResponseDTO.js
  src/app/main/mainRoute.js
  src/app/main/mainService.js
Labels: ✨ Feat

#69 [Refactoring] : refresh token 도입
  config/jwtMiddleWare.js
  config/response.js
  src/app/user/userController.js
  src/app/user/userDao.js
  src/app/user/userRoute.js
  src/app/user/userService.js
Labels: 🔨 Refactoring

#74 [Refactoring] : 쿠키 response 내용 추가 쿠키 response 내용 추가, 주석 삭제
  config/express.js
  package.json
  src/app/user/userController.js
  src/app/user/userRoute.js
Labels: 🚑 Bug Fix, 🔨 Refactoring

#75 [Refactoring] : refresh token 재발급 코드 cookie 읽어오기
  src/app/user/userController.js
Labels: 🔨 Refactoring
